// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFile(arg1, arg2) {
  return window['go']['main']['App']['AddFile'](arg1, arg2);
}

export function AddFolder(arg1) {
  return window['go']['main']['App']['AddFolder'](arg1);
}
